/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Decode an audio file and report its duration, rate and loudness stats. */
export declare function audioStats(path: string): AudioStatsInfo

/** Audio decode statistics (mirrors the CLI's `audio-check` output). */
export interface AudioStatsInfo {
  bytes: number
  duration: number
  sampleRate: number
  channels: number
  layout: string
  frames: number
  peak: number
  rms: number
  mean: number
}

/**
 * Compose several SVG scenes into one MP4 with an audio-driven timeline.
 * `manifest_path` points to a JSON manifest — see the CLI's
 * `compose --help` for the schema; every path is resolved against the
 * manifest's directory.
 */
export declare function compose(manifestPath: string, out?: string | undefined | null): ComposeReportInfo

/** Report of a finished `compose` run (mirrors the CLI's summary). */
export interface ComposeReportInfo {
  /** The produced MP4 path. */
  out: string
  scenes: number
  frames: number
  fps: number
  /** Video track duration in seconds (measured from the produced file). */
  videoDuration: number
  /** Audio track duration in seconds (decoded from the output file). */
  audioDuration: number
  /** Planned total window length in seconds (Σ scene windows). */
  duration: number
  codec: string
  threads: number
}

/**
 * Inspect an image's pixels: dimensions, color stats, a specific pixel
 * (`"x,y"`) and the bounding box of the pixels differing from `background`
 * (#RRGGBB). Mirrors the CLI's `image-check`.
 */
export declare function imageStats(path: string, pixel?: string | undefined | null, background?: string | undefined | null): ImageStatsInfo

/** Image pixel statistics (mirrors the CLI's `image-check` output). */
export interface ImageStatsInfo {
  width: number
  height: number
  colorType: string
  bytes: number
  /** Mean of each RGBA channel (0-255). */
  avgRgba: Array<number>
  /** Number of distinct RGBA colors (capped; see `unique_capped`). */
  uniqueColors: number
  uniqueCapped: boolean
  translucentPixels: number
  uniform: boolean
  uniformColor?: Array<number>
  queriedPixel?: Array<number>
  /** Inclusive bounding box `(x0, y0, x1, y1)` of the foreground pixels. */
  contentBbox?: Array<number>
}

/**
 * List the voices available on the server (`short_name` is what `tts`'s
 * `voice` option should receive).
 */
export declare function listVoices(): Array<VoiceInfo>

/** Mux a video and one or more audio files (concatenated in order) into an MP4. */
export declare function merge(video: string, audio: Array<string>, out: string, opts?: MergeOptions | undefined | null): void

/** Options for `merge`. */
export interface MergeOptions {
  /** Video stream handling: `copy` (default, no re-encode) or a codec name. */
  videoCodec?: string
  /** Audio stream handling: `aac` (default, re-encoded) or `copy`. */
  audioCodec?: string
  /**
   * Insert this many seconds of silence between every concatenated audio
   * segment and after the last one (multi-audio only).
   */
  pad?: number
  /**
   * Normalize every audio segment's loudness to this target (LUFS,
   * e.g. -14) — evens out per-page TTS volume differences and forces
   * audio re-encoding (no `copy`).
   */
  loudnorm?: number
}

/**
 * Read a media file's duration in seconds (via FFmpeg's demuxer), mirroring
 * the CLI's post-`tts` duration report.
 */
export declare function probeDuration(path: string): number

/** Render a single frame at `time` (seconds) and return the PNG bytes. */
export declare function renderFrame(svg: string, time: number, opts?: RenderOptions | undefined | null): Buffer

/**
 * Render the whole animation and return every frame as PNG bytes (memory
 * grows with frame count; for long exports prefer `renderMp4` or repeated
 * `renderFrame` calls).
 */
export declare function renderFrames(svg: string, opts?: RenderOptions | undefined | null): Array<Buffer>

/**
 * Render an SVG animation to an MP4 file at `out`; returns the effective
 * video codec used (the requested codec, or `mpeg4` when it was unavailable).
 */
export declare function renderMp4(svg: string, out: string, opts?: RenderOptions | undefined | null): string

/** Options shared by the rendering functions. */
export interface RenderOptions {
  /**
   * Directory that relative references (images, `@font-face`, external
   * `<use>`) resolve against; defaults to the current directory.
   */
  baseDir?: string
  /** Frame rate (frames per second), default 30. */
  fps?: number
  /** Export duration in seconds; defaults to the animation's own duration. */
  duration?: number
  /** Start time (seconds) of the rendered window (default 0). */
  start?: number
  /**
   * End time (seconds) of the rendered window; defaults to the
   * animation's own duration (or `duration` when given).
   */
  end?: number
  /** Resolution multiplier (1.0 = document intrinsic size). */
  scale?: number
  /** Parallel render threads (default 1). */
  threads?: number
  /** Video codec for `renderMp4` (default `libx264`, falls back to `mpeg4`). */
  videoCodec?: string
  /**
   * Quality 0-51 for `renderMp4`: CRF for the x264 family (lower =
   * sharper, default 10); mapped to a fixed quantizer for mpeg4.
   */
  crf?: number
  /**
   * Background color for `renderMp4` transparent regions (#RRGGBB,
   * default #000000).
   */
  background?: string
  /** Path to an .srt/.ass file to burn into the video (`renderMp4` only). */
  subtitle?: string
  /**
   * Font file for subtitle rendering (recommended for CJK text; when
   * given, only this font is used, making output deterministic).
   */
  subtitleFont?: string
}

/**
 * Scaled (even-rounded) pixel dimensions: document size x scale. yuv420p
 * (H.264/mpeg4) requires even width/height, so odd values are rounded down.
 * Shared with the CLI via `render::scaled_dimensions`.
 */
export declare function scaledSize(width: number, height: number, scale: number): number[]

/**
 * Generate SRT subtitle text from narration text and the word-boundary JSON
 * written by `ttsWithBoundaries` / the CLI's `tts --word-boundaries`.
 */
export declare function srtGenerate(text: string, boundariesJson: string): string

/** Parse an SVG and report its intrinsic size and animation duration. */
export declare function svgInfo(svg: string, opts?: RenderOptions | undefined | null): SvgInfo

/** Metadata about an SVG document. */
export interface SvgInfo {
  /** Document width in pixels (intrinsic size, before scaling). */
  width: number
  /** Document height in pixels (intrinsic size, before scaling). */
  height: number
  /** Total animation duration in seconds (0 for static documents). */
  duration: number
  /** Whether the document contains SMIL animations. */
  hasAnimation: boolean
}

/** Synthesize narration audio for `text` and return the audio bytes. */
export declare function tts(text: string, opts?: TtsOptions | undefined | null): Buffer

/** Options for `tts`. */
export interface TtsOptions {
  /** Voice (default `zh-CN-XiaoxiaoNeural`; see `listVoices`). */
  voice?: string
  /** Speech rate in percent (e.g. 10 = +10%). */
  rate?: number
  /** Pitch in Hz. */
  pitch?: number
  /** Volume in percent. */
  volume?: number
  /** Audio output format (default `webm-24khz-16bit-mono-opus`). */
  format?: string
}

/**
 * Synthesize narration audio and also return the service's per-word
 * boundary events (for precise subtitle timing).
 */
export declare function ttsWithBoundaries(text: string, opts?: TtsOptions | undefined | null): TtsWithBoundariesResult

/** Result of `ttsWithBoundaries`: the audio bytes plus per-word timing. */
export interface TtsWithBoundariesResult {
  audio: Buffer
  wordBoundaries: Array<WordBoundaryInfo>
  /**
   * Measured duration in milliseconds (last word's end; 0 when the
   * service sent no word boundaries).
   */
  durationMs: number
}

/** Decode a video file and report its dimensions, timing and frame stats. */
export declare function videoStats(path: string): VideoStatsInfo

/** Video decode statistics (mirrors the CLI's `video-check` output). */
export interface VideoStatsInfo {
  bytes: number
  duration?: number
  width: number
  height: number
  frames: number
  fps?: number
  meanLuma: number
  minMeanLuma: number
  maxMeanLuma: number
  blackFrames: number
  whiteFrames: number
}

/** One available Edge TTS voice. */
export interface VoiceInfo {
  name: string
  shortName?: string
  gender?: string
  locale?: string
  friendlyName?: string
  suggestedCodec?: string
  status?: string
}

/** One word-boundary event from the Edge TTS service. */
export interface WordBoundaryInfo {
  /** When the word started, in milliseconds from the start of the audio. */
  startMs: number
  /** When the word finished (`start_ms + duration_ms`). */
  endMs: number
  /** How long the word took, in milliseconds. */
  durationMs: number
  /** The word's text. */
  text: string
}
